# fly.toml app configuration file generated for reversi-frame on 2024-02-26T11:20:54+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reversi-frame'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
